server:
  port: 8888

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/gzmu_auth?useUnicode=true&characterEncoding=UTF-8&useOldAliasMetadataBehavior=true&autoReconnect=true&serverTimezone=UTC
    username: root
    password: 123456
    druid:
      filters: stat,wall,commonlogging
      web-stat-filter:
        enabled: true
      stat-view-servlet:
        enabled: true
        login-password: 123456
        login-username: admin
        url-pattern: /druid/*
        allow: 127.0.0.1
  jpa:
    open-in-view: true
    show-sql: true
  mail:
    host: smtp.exmail.qq.com
    port: 465
    username: lessonCloud@japoul.cn
    password: lessonC2019
    properties:
      mail:
        debug: false
        smtp:
          auth: true
          starttls:
            required: true
          socketFactory:
            class: javax.net.ssl.SSLSocketFactory
    test-connection: false
  redis:
    host: 127.0.0.1
    password:
management:
  endpoints:
    web:
      exposure:
        include: "*"
application:
  security:
    access-token-validity-seconds: 60
  message:
    app-id: 35223
    app-key: e7eede1811867421882df861a20ed26e
    action-template: RhXa91

#logging:
#  level:
#    org:
#      springframework:
#        security: debug
