server:
  port: 8888

spring:
  profiles:
    active: dev
  data:
    rest:
      base-path: /api
      default-page-size: 10
      sort-param-name: id
  main:
    allow-bean-definition-overriding: true
  jpa:
    open-in-view: true
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
  mail:
    host: smtp.exmail.qq.com
    port: 465
    username: lessonCloud@japoul.cn
    password: lessonC2019
    properties:
      mail:
        debug: false
        smtp:
          auth: true
          starttls:
            required: true
          socketFactory:
            class: javax.net.ssl.SSLSocketFactory
    test-connection: false
  application:
    name: gzmu-auth
  session:
    redis:
      namespace: gzmu-auth
    store-type: redis
management:
  endpoints:
    web:
      exposure:
        include: "*"
application:
  security:
    access-token-validity-seconds: 60
  sms:
    dev: true
    app-id: 35223
    app-key: e7eede1811867421882df861a20ed26e
    action-template: RhXa91
  email:
    dev: true
logging:
  level:
    org.springframework.boot.actuate.endpoint.EndpointId: error
    org.springframework.context.support.[PostProcessorRegistrationDelegate$BeanPostProcessorChecker]: warn
  file:
    name: logs/auth-server.log
