spring:
  profiles: dev
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://118.24.1.170:5432/gzmu
    username: postgres
    password: 147258369
    druid:
      filters: stat,wall,commonlogging
      web-stat-filter:
        enabled: true
      stat-view-servlet:
        enabled: true
        login-password: 123456
        login-username: admin
        url-pattern: /druid/*
        allow: 127.0.0.1
logging:
  level:
    cn.edu.gzmu.authserver: debug
